-- ============================================
-- Phase 1: update_policy 테이블 생성
-- 작성일: 2025-11-09
-- 목적: 업데이트 정책 분리 및 단순화
-- ============================================

-- 0. 기존 테이블 삭제 (있으면)
DROP TABLE IF EXISTS public.update_policy CASCADE;

-- 1. update_policy 테이블 생성
CREATE TABLE public.update_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- 기본 정보
    app_id TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    -- ===== 핵심 필드 (단순화!) =====
    target_version_code INT NOT NULL,        -- 목표 버전 (단일 필드!)
    is_force_update BOOLEAN NOT NULL,        -- 강제 업데이트 여부

    -- 부가 정보
    release_notes TEXT,                      -- 릴리즈 노트 (선택적)
    download_url TEXT NOT NULL DEFAULT 'https://play.google.com/',  -- Play Store 링크

    CONSTRAINT update_policy_pkey PRIMARY KEY (id)
);

-- 2. 인덱스 생성
CREATE INDEX idx_update_policy_app_id ON public.update_policy(app_id);
CREATE INDEX idx_update_policy_active ON public.update_policy(is_active);

-- 앱당 1개의 활성 정책만 허용 (partial unique index)
CREATE UNIQUE INDEX idx_update_policy_unique_active
ON public.update_policy(app_id)
WHERE is_active = true;

-- 3. RLS 정책 설정
ALTER TABLE public.update_policy ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow_read_update_policy"
ON public.update_policy
FOR SELECT
USING (true);

-- 4. 코멘트 추가
COMMENT ON TABLE public.update_policy IS '앱 업데이트 정책 (강제/선택적 업데이트)';
COMMENT ON COLUMN public.update_policy.target_version_code IS '목표 버전 코드 (현재 버전 < 목표 버전이면 업데이트 필요)';
COMMENT ON COLUMN public.update_policy.is_force_update IS '강제 업데이트 여부 (true: 강제, false: 선택적)';

-- 5. 테스트 데이터 삽입 (PocketChord 앱)
INSERT INTO public.update_policy (
    app_id,
    is_active,
    target_version_code,
    is_force_update,
    release_notes,
    download_url
) VALUES (
    'com.sweetapps.pocketchord',
    true,
    1,  -- 현재 버전보다 낮게 설정 (업데이트 팝업 안 뜸)
    false,
    '• 성능 개선\n• 버그 수정',
    'https://play.google.com/store/apps/details?id=com.sweetapps.pocketchord'
);

-- 테스트용 debug 데이터
INSERT INTO public.update_policy (
    app_id,
    is_active,
    target_version_code,
    is_force_update,
    release_notes,
    download_url
) VALUES (
    'com.sweetapps.pocketchord.debug',
    false,  -- 비활성화 (테스트 시 수동으로 활성화)
    999,    -- 높은 버전 (테스트용)
    false,
    '• [DEBUG] 테스트 기능 1\n• [DEBUG] 테스트 기능 2',
    'https://play.google.com/store/apps/details?id=com.sweetapps.pocketchord.debug'
);

-- 완료!
SELECT 'update_policy 테이블 생성 완료!' as status;

