-- ============================================
-- Phase 2: emergency_policy 테이블 생성
-- 작성일: 2025-11-09
-- 목적: 긴급 상황 분리 및 Google Play 정책 준수
-- ============================================

-- 1. emergency_policy 테이블 생성
CREATE TABLE public.emergency_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- 기본 정보
    app_id TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    -- 긴급 메시지
    content TEXT NOT NULL,
    redirect_url TEXT,
    new_app_id TEXT,

    -- ===== Google Play 정책 준수 (핵심!) =====
    is_dismissible BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT emergency_policy_pkey PRIMARY KEY (id),
    -- 앱당 1개의 활성 긴급 상황만 허용
    CONSTRAINT emergency_policy_unique_active
        UNIQUE (app_id, is_active)
        WHERE is_active = true
);

-- 2. 인덱스 생성
CREATE INDEX idx_emergency_policy_app_id ON public.emergency_policy(app_id);
CREATE INDEX idx_emergency_policy_active ON public.emergency_policy(is_active);

-- 3. RLS 정책 설정
ALTER TABLE public.emergency_policy ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow_read_emergency_policy"
ON public.emergency_policy
FOR SELECT
USING (true);

-- 4. 코멘트 추가
COMMENT ON TABLE public.emergency_policy IS '긴급 상황 팝업 정책 (앱 차단, 서비스 종료 등)';
COMMENT ON COLUMN public.emergency_policy.is_dismissible IS 'X 버튼 허용 여부 (기본값 true, false는 최후의 수단)';

-- 5. 테스트 데이터 삽입 (비활성화 상태)
-- 실제 긴급 상황이 아니므로 is_active = false
INSERT INTO public.emergency_policy (
    app_id,
    is_active,
    content,
    redirect_url,
    is_dismissible
) VALUES (
    'com.sweetapps.pocketchord',
    false,  -- 비활성화 (테스트용)
    '⚠️ [테스트] 이 앱은 더 이상 지원되지 않습니다.\n새 버전을 설치해주세요.',
    'https://play.google.com/store/apps/details?id=com.sweetapps.pocketchord',
    true    -- X 버튼 허용 (Google Play 정책 준수)
);

-- 완료!
SELECT 'emergency_policy 테이블 생성 완료!' as status;

