-- ============================================
-- Phase 3: notice_policy 테이블 생성
-- 작성일: 2025-11-09
-- 목적: 공지사항 분리 및 버전 관리
-- ============================================

-- 1. notice_policy 테이블 생성
CREATE TABLE public.notice_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- 기본 정보
    app_id TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    -- 공지 내용
    title TEXT,
    content TEXT NOT NULL,

    -- ===== 핵심: 버전 관리 (명시적 제어!) =====
    notice_version INTEGER NOT NULL DEFAULT 1,

    -- 부가 정보 (선택적)
    image_url TEXT,
    action_url TEXT,

    CONSTRAINT notice_policy_pkey PRIMARY KEY (id),
    -- 앱당 1개의 활성 공지만 허용
    CONSTRAINT notice_policy_unique_active
        UNIQUE (app_id, is_active)
        WHERE is_active = true
);

-- 2. 인덱스 생성
CREATE INDEX idx_notice_policy_app_id ON public.notice_policy(app_id);
CREATE INDEX idx_notice_policy_active ON public.notice_policy(is_active);

-- 3. RLS 정책 설정
ALTER TABLE public.notice_policy ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow_read_notice_policy"
ON public.notice_policy
FOR SELECT
USING (true);

-- 4. 코멘트 추가
COMMENT ON TABLE public.notice_policy IS '일반 공지사항 팝업 정책 (이벤트, 신규 기능 안내 등)';
COMMENT ON COLUMN public.notice_policy.notice_version IS '공지 버전 (증가 시 모든 사용자에게 재표시)';

-- 5. 테스트 데이터 삽입
INSERT INTO public.notice_policy (
    app_id,
    is_active,
    title,
    content,
    notice_version
) VALUES (
    'com.sweetapps.pocketchord',
    true,
    '환영합니다! 🎉',
    'PocketChord를 이용해 주셔서 감사합니다!\n더 나은 서비스를 제공하기 위해 노력하겠습니다.',
    1  -- 버전 1
);

-- 완료!
SELECT 'notice_policy 테이블 생성 완료!' as status;

