package com.sweetapps.pocketchord.data.supabase.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 공지사항 모델
 *
 * Supabase 테이블 구조 (announcements):
 * ```sql
 * CREATE TABLE public.announcements (
 *     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 *     created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
 *     app_id TEXT NOT NULL,
 *     title TEXT NOT NULL,
 *     content TEXT NOT NULL,
 *     is_active BOOLEAN NOT NULL DEFAULT TRUE,
 *     CONSTRAINT announcements_pkey PRIMARY KEY (id)
 * )
 * ```
 *
 * 용도:
 * - 앱 내 팝업 공지사항
 * - 배너 알림
 * - 뉴스 피드
 * - 이벤트 안내
 *
 * 사용 예시:
 * ```kotlin
 * val announcements = supabase.from("announcements")
 *     .select()
 *     .eq("app_id", "pocketchord")
 *     .eq("is_active", true)
 *     .order("created_at", descending = true)
 *     .decodeList<Announcement>()
 * ```
 */
@Serializable
data class Announcement(
    /**
     * 공지사항 ID (자동 생성)
     */
    @SerialName("id")
    val id: Long? = null,

    /**
     * 생성 시간 (ISO 8601 형식)
     * 예: "2025-11-05T10:30:00Z"
     */
    @SerialName("created_at")
    val createdAt: String? = null,

    /**
     * 앱 식별자
     * 하나의 Supabase 프로젝트에서 여러 앱을 관리할 때 사용
     * 기본값: 빌드타입별 BuildConfig.SUPABASE_APP_ID
     */
    @SerialName("app_id")
    val appId: String = com.sweetapps.pocketchord.BuildConfig.SUPABASE_APP_ID,

    /**
     * 공지사항 제목
     * 예: "새로운 기능 업데이트!", "12월 이벤트 안내"
     */
    @SerialName("title")
    val title: String,

    /**
     * 공지사항 내용
     * Markdown 형식 지원 가능
     */
    @SerialName("content")
    val content: String,

    /**
     * 활성화 여부
     * - true: 앱에 표시
     * - false: 숨김 (관리자만 확인 가능)
     */
    @SerialName("is_active")
    val isActive: Boolean = true,

    /**
     * 공지 유형 (announcement | emergency)
     */
    @SerialName("kind")
    val kind: String = "announcement",

    /**
     * 리다이렉트 URL (긴급 안내에서 사용)
     */
    @SerialName("redirect_url")
    val redirectUrl: String? = null,

    /**
     * 닫기 가능 여부 (긴급 안내는 false가 일반적)
     */
    @SerialName("dismissible")
    val dismissible: Boolean = true,

    /**
     * 노출 기간(선택)
     */
    @SerialName("start_at")
    val startAt: String? = null,
    @SerialName("end_at")
    val endAt: String? = null
) {
    val isEmergency: Boolean get() = kind.equals("emergency", ignoreCase = true)
}
