package com.sweetapps.pocketchord.data.supabase.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 긴급 상황 정책 모델
 *
 * Supabase 테이블 구조 (emergency_policy):
 * ```sql
 * CREATE TABLE public.emergency_policy (
 *     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 *     created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
 *     app_id TEXT NOT NULL,
 *     is_active BOOLEAN NOT NULL DEFAULT TRUE,
 *     content TEXT NOT NULL,
 *     redirect_url TEXT,
 *     button_text TEXT,
 *     is_dismissible BOOLEAN NOT NULL DEFAULT TRUE,
 *     CONSTRAINT emergency_policy_pkey PRIMARY KEY (id)
 * )
 * ```
 *
 * 사용 목적:
 * - 앱이 플레이스토어에서 차단된 경우
 * - 서비스 종료 안내
 * - 강제 마이그레이션 (새 앱으로 이동)
 *
 * 핵심 기능:
 * - is_dismissible: X 버튼 제어 (Google Play 정책 준수)
 * - 추적 없음: 매번 표시 (사용자가 조치 취할 때까지)
 * - 최우선순위: 다른 모든 팝업보다 우선
 *
 * 사용 예시:
 * ```kotlin
 * val emergency = emergencyPolicyRepository.getActiveEmergency()
 *
 * emergency?.let {
 *     EmergencyRedirectDialog(
 *         description = it.content,
 *         redirectUrl = it.redirectUrl,
 *         isDismissible = it.isDismissible,  // ← DB에서 제어!
 *         onDismiss = if (it.isDismissible) { ... } else null
 *     )
 * }
 * ```
 */
@Serializable
data class EmergencyPolicy(
    /**
     * 정책 ID (자동 생성)
     */
    @SerialName("id")
    val id: Long? = null,

    /**
     * 생성 시간 (ISO 8601 형식)
     * 예: "2025-11-09T10:30:00Z"
     */
    @SerialName("created_at")
    val createdAt: String? = null,

    /**
     * 앱 ID (패키지명)
     * 예: "com.sweetapps.pocketchord"
     */
    @SerialName("app_id")
    val appId: String,

    /**
     * 활성화 여부
     * - true: 긴급 상황 활성화 (팝업 표시)
     * - false: 긴급 상황 해제 (팝업 표시 안 함)
     */
    @SerialName("is_active")
    val isActive: Boolean = false,

    /**
     * 긴급 메시지
     *
     * 예시:
     * - "⚠️ 이 앱은 더 이상 지원되지 않습니다.\n새 버전을 설치해주세요."
     * - "🚨 서비스 종료 안내\n2025년 12월 31일부로 서비스가 종료됩니다."
     */
    @SerialName("content")
    val content: String,

    /**
     * 리다이렉트 URL
     *
     * 사용자가 버튼 클릭 시 이동할 URL
     * 예: "https://play.google.com/store/apps/details?id=com.sweetapps.newapp"
     */
    @SerialName("redirect_url")
    val redirectUrl: String? = null,

    /**
     * 버튼 텍스트
     *
     * "확인" 버튼의 텍스트를 설정
     * 예: "확인", "새 앱 설치하기", "자세히 보기"
     * 기본값: "확인"
     */
    @SerialName("button_text")
    val buttonText: String = "확인",

    // ===== Google Play 정책 준수 (핵심!) =====

    /**
     * X 버튼 허용 여부
     *
     * Google Play 정책:
     * "사용자가 원하지 않는 경우 대화상자나 전체 화면 메시지를 닫을 수 있어야 합니다."
     *
     * 권장 사용:
     * - true (기본값): X 버튼 표시 (Google Play 정책 준수) ✅
     * - false: X 버튼 숨김 (최후의 수단, 정책 위반 가능성) ⚠️
     *
     * 예시:
     * - 서비스 종료 예정 (선택 가능): true
     * - 앱 완전 차단 (강제): false (주의!)
     */
    @SerialName("is_dismissible")
    val isDismissible: Boolean = true
)

