package com.sweetapps.pocketchord.data.supabase.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 공지사항 정책 모델 (버전 관리)
 *
 * Supabase 테이블 구조 (notice_policy):
 * ```sql
 * CREATE TABLE public.notice_policy (
 *     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 *     created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
 *     app_id TEXT NOT NULL,
 *     is_active BOOLEAN NOT NULL DEFAULT TRUE,
 *     title TEXT,
 *     content TEXT NOT NULL,
 *     notice_version INTEGER NOT NULL DEFAULT 1,
 *     image_url TEXT,
 *     action_url TEXT,
 *     CONSTRAINT notice_policy_pkey PRIMARY KEY (id)
 * )
 * ```
 *
 * 사용 목적:
 * - 일반 공지사항 (이벤트, 신규 기능 안내 등)
 * - 월별/시즌별 공지
 * - 업데이트 안내 (선택적 정보)
 *
 * 핵심 기능:
 * - notice_version: 버전 관리로 명시적 제어
 * - 오타 수정: 버전 유지 → 재표시 안 됨
 * - 새 공지: 버전 증가 → 모두에게 재표시
 *
 * 추적 메커니즘:
 * - SharedPreferences에 "notice_v1", "notice_v2" 형식으로 저장
 * - 버전이 증가하면 새 식별자 → 재표시됨
 *
 * 사용 예시:
 * ```kotlin
 * val notice = noticePolicyRepository.getActiveNotice()
 *
 * notice?.let {
 *     val identifier = "notice_v${it.noticeVersion}"
 *     val prefs = context.getSharedPreferences("notice_prefs", Context.MODE_PRIVATE)
 *     val viewedVersions = prefs.getStringSet("viewed_notices", setOf()) ?: setOf()
 *
 *     if (!viewedVersions.contains(identifier)) {
 *         // 새 버전 → 공지 표시
 *         showNoticeDialog(it)
 *     }
 * }
 * ```
 *
 * 운영 예시:
 * ```sql
 * -- 오타 수정 (버전 유지)
 * UPDATE notice_policy SET content = '수정된 내용' WHERE app_id = '...';
 * -- notice_version = 1 (그대로) → 이미 본 사용자에게 안 뜸
 *
 * -- 새 공지 (버전 증가)
 * UPDATE notice_policy
 * SET content = '2월 이벤트', notice_version = 2
 * WHERE app_id = '...';
 * -- notice_version = 2 → 모든 사용자에게 재표시!
 * ```
 */
@Serializable
data class NoticePolicy(
    /**
     * 정책 ID (자동 생성)
     */
    @SerialName("id")
    val id: Long? = null,

    /**
     * 생성 시간 (ISO 8601 형식)
     * 예: "2025-11-09T10:30:00Z"
     */
    @SerialName("created_at")
    val createdAt: String? = null,

    /**
     * 앱 ID (패키지명)
     * 예: "com.sweetapps.pocketchord"
     */
    @SerialName("app_id")
    val appId: String,

    /**
     * 활성화 여부
     * - true: 공지 활성화 (팝업 표시 가능)
     * - false: 공지 비활성화 (팝업 표시 안 함)
     */
    @SerialName("is_active")
    val isActive: Boolean = false,

    /**
     * 공지 제목 (선택적)
     *
     * 예시:
     * - "🎉 신년 이벤트"
     * - "💝 밸런타인 데이 특가"
     * - "📢 새로운 기능 안내"
     */
    @SerialName("title")
    val title: String? = null,

    /**
     * 공지 내용
     *
     * 예시:
     * - "새해 맞이 50% 특별 할인!"
     * - "다크 모드가 추가되었습니다.\n설정에서 활성화해보세요."
     */
    @SerialName("content")
    val content: String,

    // ===== 핵심: 버전 관리 (명시적 제어!) =====

    /**
     * 공지 버전
     *
     * 사용법:
     * - 오타 수정: 버전 유지 (notice_version 그대로)
     * - 새 공지: 버전 증가 (notice_version + 1)
     *
     * 예시:
     * - 1월 공지: notice_version = 1
     * - 오타 수정: notice_version = 1 (그대로) → 재표시 안 됨 ✅
     * - 2월 공지: notice_version = 2 (증가) → 모두에게 재표시 ✅
     *
     * 추적 식별자:
     * - "notice_v1", "notice_v2", "notice_v3" ...
     */
    @SerialName("notice_version")
    val noticeVersion: Int = 1
)

