package com.sweetapps.pocketchord.data.supabase.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 업데이트 정책 모델 (단순화된 구조)
 *
 * Supabase 테이블 구조 (update_policy):
 * ```sql
 * CREATE TABLE public.update_policy (
 *     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 *     created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
 *     app_id TEXT NOT NULL,
 *     is_active BOOLEAN NOT NULL DEFAULT TRUE,
 *     target_version_code INT NOT NULL,
 *     is_force_update BOOLEAN NOT NULL,
 *     message TEXT,
 *     release_notes TEXT,
 *     download_url TEXT,
 *     CONSTRAINT update_policy_pkey PRIMARY KEY (id)
 * )
 * ```
 *
 * 핵심 개선사항:
 * - min_supported_version + latest_version_code (2개 필드)
 *   → target_version_code (1개 필드)로 단순화
 * - active_popup_type ('force_update' | 'optional_update')
 *   → is_force_update (Boolean)로 명확화
 *
 * 사용 예시:
 * ```kotlin
 * val policy = updatePolicyRepository.getPolicy()
 *
 * when {
 *     policy.requiresForceUpdate(currentVersion) -> {
 *         // 강제 업데이트 팝업 표시
 *     }
 *     policy.recommendsOptionalUpdate(currentVersion) -> {
 *         // 선택적 업데이트 팝업 표시
 *     }
 * }
 * ```
 */
@Serializable
data class UpdatePolicy(
    /**
     * 정책 ID (자동 생성)
     */
    @SerialName("id")
    val id: Long? = null,

    /**
     * 생성 시간 (ISO 8601 형식)
     * 예: "2025-11-09T10:30:00Z"
     */
    @SerialName("created_at")
    val createdAt: String? = null,

    /**
     * 앱 ID (패키지명)
     * 예: "com.sweetapps.pocketchord"
     */
    @SerialName("app_id")
    val appId: String,

    /**
     * 활성화 여부
     * - true: 정책 활성화 (팝업 표시 가능)
     * - false: 정책 비활성화 (팝업 표시 안 함)
     */
    @SerialName("is_active")
    val isActive: Boolean = false,

    // ===== 핵심 필드 (단순화!) =====

    /**
     * 목표 버전 코드 (단일 필드!)
     *
     * 사용법:
     * - 강제 업데이트: currentVersion < targetVersionCode
     * - 선택적 업데이트: currentVersion < targetVersionCode
     *
     * 예시:
     * - target_version_code = 10
     * - 현재 버전 8 → 업데이트 필요
     * - 현재 버전 10 → 업데이트 불필요
     * - 현재 버전 12 → 업데이트 불필요
     */
    @SerialName("target_version_code")
    val targetVersionCode: Int,

    /**
     * 강제 업데이트 여부
     * - true: 강제 업데이트 (X 버튼 없음, 뒤로가기 차단)
     * - false: 선택적 업데이트 ("나중에" 버튼 있음)
     */
    @SerialName("is_force_update")
    val isForceUpdate: Boolean,

    // ===== 부가 정보 =====

    /**
     * 릴리즈 노트
     * 업데이트 내용 상세 설명 (줄바꿈으로 구분)
     * 예: "• 새로운 기능 추가\n• 버그 수정\n• 성능 개선"
     */
    @SerialName("release_notes")
    val releaseNotes: String? = null,

    /**
     * 다운로드 URL
     * Play Store 링크 (필수)
     * 기본값: https://play.google.com/
     */
    @SerialName("download_url")
    val downloadUrl: String = "https://play.google.com/",

    // ===== Phase 2.5: 시간 기반 재표시 필드 =====

    /**
     * 재표시 간격 (시간 단위)
     * "나중에" 클릭 후 다시 팝업을 표시할 때까지의 시간
     * 기본값: 24시간
     *
     * 예시:
     * - 24: 24시간(1일) 후 재표시
     * - 1: 1시간 후 재표시 (테스트용)
     */
    @SerialName("reshow_interval_hours")
    val reshowIntervalHours: Int? = 24,

    /**
     * 재표시 간격 (분 단위) - 테스트 전용
     * 우선순위: reshow_interval_seconds > reshow_interval_minutes > reshow_interval_hours
     * NULL이면 하위 단위 사용
     *
     * 사용 예시:
     * - NULL: hours 사용 (운영 환경)
     * - 5: 5분 후 재표시 (빠른 테스트용)
     * - 30: 30분 후 재표시
     *
     * ⚠️ 주의: 운영 환경에서는 항상 NULL로 설정해야 함
     */
    @SerialName("reshow_interval_minutes")
    val reshowIntervalMinutes: Int? = null,

    /**
     * 재표시 간격 (초 단위) - 초고속 테스트 전용
     * 우선순위: 최우선 (seconds > minutes > hours)
     * NULL이면 minutes 또는 hours 사용
     *
     * 사용 예시:
     * - NULL: minutes/hours 사용 (운영 환경)
     * - 30: 30초 후 재표시 (초고속 테스트용)
     * - 60: 1분 후 재표시
     *
     * ⚠️ 주의: 운영 환경에서는 항상 NULL로 설정해야 함
     */
    @SerialName("reshow_interval_seconds")
    val reshowIntervalSeconds: Int? = null,

    /**
     * 최대 "나중에" 허용 횟수
     * 이 횟수에 도달하면 강제 업데이트로 전환
     * 기본값: 3회
     *
     * 예시:
     * - 3: "나중에" 3회 클릭 후 강제 전환
     * - 1: "나중에" 1회만 허용
     */
    @SerialName("max_later_count")
    val maxLaterCount: Int? = 3
) {
    /**
     * 업데이트가 필요한지 확인
     * @param currentVersionCode 현재 앱 버전 코드
     * @return true: 업데이트 필요, false: 업데이트 불필요
     */
    fun needsUpdate(currentVersionCode: Int): Boolean {
        return currentVersionCode < targetVersionCode
    }

    /**
     * 강제 업데이트가 필요한지 확인
     * @param currentVersionCode 현재 앱 버전 코드
     * @return true: 강제 업데이트 필요, false: 강제 업데이트 불필요
     */
    fun requiresForceUpdate(currentVersionCode: Int): Boolean {
        return isForceUpdate && needsUpdate(currentVersionCode)
    }

    /**
     * 선택적 업데이트 권장 여부
     * @param currentVersionCode 현재 앱 버전 코드
     * @return true: 선택적 업데이트 권장, false: 권장하지 않음
     */
    fun recommendsOptionalUpdate(currentVersionCode: Int): Boolean {
        return !isForceUpdate && needsUpdate(currentVersionCode)
    }
}

